# picoruby-asterism-zenoh: Zenoh (zenoh-pico) client for PicoRuby / mruby.
#
# The zenoh-pico sources are compiled into this gem. Where they come from:
#   1. ZENOH_PICO_DIR (a zenoh-pico checkout), or
#   2. vendor/zenoh-pico inside this gem (src/ and include/ of a release).
# The gem does not fetch anything itself; the host build puts the sources in
# place. The release the gem is written against is pinned in ZENOH_PICO_PIN
# (this repository's `rake zenoh:fetch` clones it into vendor/zenoh-pico;
# Family mruby: `rake zenoh:setup` + `rake setup`, see README.md).
#
# Platforms (zenoh-pico's platform selector, ZENOH_PICO_PLATFORM overrides):
# - POSIX (ZENOH_LINUX, or ZENOH_MACOS / ZENOH_BSD): everything is compiled
#   here, with this gem's src/zp_tcp_posix.c as the TCP link and
#   src/zp_network_posix.c as the socket helpers.
# - ESP-IDF (ZENOH_ESPIDF, chosen for build names starting with "esp32"): the
#   zenoh-pico core and the gem are compiled here with the platform types of
#   include/zenoh_espidf_platform.h, which need no ESP-IDF headers. The
#   platform files that do (ports/esp32/: system with a PSRAM allocator, the
#   TCP link; and zenoh-pico's src/system/socket/esp32.c) are left to the
#   ESP-IDF component, like the ports/esp32 sources of other PicoRuby gems.
#   They must be compiled with the same defines and include paths; see
#   README.md (Building).
MRuby::Gem::Specification.new('picoruby-asterism-zenoh') do |spec|
  # MIT for the gem's own code; Apache-2.0 for the files derived from
  # zenoh-pico and for zenoh-pico itself, compiled in (README.md, License).
  spec.licenses = ['MIT', 'Apache-2.0']
  spec.authors = ['Katsuhiko Kageyama']
  spec.summary = 'Zenoh (put, subscribe, query, liveliness) on zenoh-pico, polled from Ruby'

  zp_dir = ENV['ZENOH_PICO_DIR'].to_s
  zp_dir = File.join(dir, 'vendor', 'zenoh-pico') if zp_dir.empty?
  unless File.exist?(File.join(zp_dir, 'include', 'zenoh-pico.h'))
    raise "picoruby-asterism-zenoh: zenoh-pico sources not found at #{zp_dir} " \
          "(set ZENOH_PICO_DIR or copy zenoh-pico's src/ and include/ there)"
  end

  # Build options (see include/zenoh_generic_config.h for the feature set).
  # ZENOH_GENERIC makes zenoh-pico's config.h take the values from that file
  # instead of the CMake-generated block.
  #
  # zenoh-pico ships include/zenoh-pico/config.h only as a CMake template
  # (config.h.in). Generate the header from it into the build directory:
  # with ZENOH_GENERIC the CMake-substituted block is skipped by the
  # preprocessor, so only the `#cmakedefine` lines need neutralising.
  gen_inc = "#{build_dir}/zp_include"
  gen_cfg = "#{gen_inc}/zenoh-pico/config.h"
  template = File.read("#{zp_dir}/include/zenoh-pico/config.h.in")
  #
  # Z_LISTEN_MAX_CONNECTION_NB (peers a listening session accepts) is a plain
  # #define in the template, not overridable from outside, so it is set here
  # while generating: 3 instead of zenoh-pico's 10. Each connected peer costs
  # internal RAM on ESP-IDF (lwIP sockets and buffers, 1.5-3 KB each), and a
  # peer does not forward, so a larger group should use a router anyway.
  # PICORUBY_ZENOH_MAX_PEERS overrides it.
  max_peers = (ENV['PICORUBY_ZENOH_MAX_PEERS'] || 3).to_i
  raise "picoruby-asterism-zenoh: PICORUBY_ZENOH_MAX_PEERS must be 1..10" unless (1..10).cover?(max_peers)
  listen_line = /^#define Z_LISTEN_MAX_CONNECTION_NB \d+$/
  raise "picoruby-asterism-zenoh: Z_LISTEN_MAX_CONNECTION_NB not found in config.h.in" unless template =~ listen_line
  generated = "/* Generated by picoruby-asterism-zenoh/mrbgem.rake from config.h.in. Do not edit. */\n" +
              template.gsub(/^#cmakedefine .*$/) { |l| "/* #{l.sub('#cmakedefine', 'cmakedefine (unused)')} */" }
                      .sub(listen_line, "#define Z_LISTEN_MAX_CONNECTION_NB #{max_peers} /* picoruby-asterism-zenoh */")
  unless File.exist?(gen_cfg) && File.read(gen_cfg) == generated
    FileUtils.mkdir_p(File.dirname(gen_cfg))
    File.write(gen_cfg, generated)
  end
  spec.cc.include_paths << "#{dir}/include"
  spec.cc.include_paths << gen_inc
  spec.cc.include_paths << "#{zp_dir}/include"
  spec.cc.defines << 'ZENOH_GENERIC'
  spec.cc.defines << 'ZENOH_C_STANDARD=11'
  spec.cc.defines << 'ZENOH_COMPILER_GCC'
  # Errors from zenoh-pico are printed (stdout); quiet otherwise.
  spec.cc.defines << 'ZENOH_LOG_ERROR'
  # zenoh-pico's platform selector (ZENOH_MACOS / ZENOH_BSD for those hosts).
  platform = ENV['ZENOH_PICO_PLATFORM'].to_s
  platform = build.name.start_with?('esp32') ? 'ZENOH_ESPIDF' : 'ZENOH_LINUX' if platform.empty?
  posix = %w[ZENOH_LINUX ZENOH_MACOS ZENOH_BSD].include?(platform)
  spec.cc.defines << platform
  # zenoh-pico is written for C11 (anonymous unions, _Generic in the API).
  spec.cc.flags << '-std=gnu11'

  # The same source set as zenoh-pico's CMakeLists.txt, plus the POSIX
  # platform files on POSIX. Its POSIX TCP link (tcp_posix.c) is replaced by
  # this gem's src/zp_tcp_posix.c (non-blocking polled read, EINTR-safe),
  # which compiles to nothing on the other platforms.
  srcs = []
  %w[api collections net protocol runtime session transport utils].each do |d|
    srcs += Dir.glob("#{zp_dir}/src/#{d}/**/*.c")
  end
  srcs += Dir.glob("#{zp_dir}/src/system/common/*.c")
  %w[link/config link/multicast link/unicast link/transport/common].each do |d|
    srcs += Dir.glob("#{zp_dir}/src/#{d}/*.c")
  end
  srcs += %w[
    link/link.c
    link/endpoint.c
    link/transport/tcp/address.c
    link/transport/upper/serial_protocol.c
    link/transport/upper/tls_stream.c
  ].map { |f| "#{zp_dir}/src/#{f}" }
  # system/unix/network.c (socket helpers) is replaced by this gem's
  # src/zp_network_posix.c (EINTR-safe wait on the peer sockets).
  if posix
    srcs += %w[system/unix/system.c].map { |f| "#{zp_dir}/src/#{f}" }
  end

  # The unicast read path waits on the peer sockets (peer mode) for
  # Z_CONFIG_SOCKET_TIMEOUT on every zp_spin_once(). With a poll of several
  # steps that would stall the caller's loop for hundreds of ms when no data
  # comes. Compile that one file with a zero wait (a readiness check); the
  # handshake keeps its socket timeout everywhere else.
  per_file_defines = {
    'transport/unicast/read.c' => ['Z_CONFIG_SOCKET_TIMEOUT=0'],
  }

  build_dir_zp = "#{build_dir}/zenoh-pico"
  srcs.sort.uniq.each do |src|
    rel = src.sub("#{zp_dir}/src/", '')
    spec.objs << "#{build_dir_zp}/#{rel.sub(/\.c\z/, '')}.o"
    file "#{build_dir_zp}/#{rel.sub(/\.c\z/, '')}.o" => src do |t|
      extra = per_file_defines[rel]
      if extra
        cc = spec.cc.dup
        cc.defines = spec.cc.defines + extra
        cc.run t.name, t.prerequisites.first
      else
        spec.cc.run t.name, t.prerequisites.first
      end
    end
  end
end
